# Generated by Django 5.2.5 on 2025-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_announcement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
